import { assertServerSupabaseEnv } from '@/lib/env/hatid-env';

/**
 * Sprint 0B placeholder.
 *
 * This is not a live Supabase server client yet. The real implementation begins
 * only after @supabase/supabase-js and @supabase/ssr are installed and the
 * lockfile is regenerated by CLI.
 */
export function createServerSupabaseBoundary() {
  const env = assertServerSupabaseEnv();

  return {
    status: 'placeholder' as const,
    url: env.supabaseUrl,
    serviceRoleConfigured: Boolean(env.supabaseServiceRoleKey),
  };
}
