-- Create Schemas & Enable Extensions

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS audit;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

-- AUDIT.EVENTS TABLE

CREATE TABLE audit.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor_id UUID,
  operation TEXT NOT NULL,
  table_name TEXT NOT NULL,
  old_record JSONB,
  new_record JSONB
);

-- Grant usage on the audit schema to the postgres user
GRANT USAGE ON SCHEMA audit TO postgres;

-- Grant insert permission on the audit.events table to the authenticated role
GRANT INSERT ON TABLE audit.events TO authenticated;

-- AUDIT TRIGGER FUNCTION

CREATE OR REPLACE FUNCTION audit.log_changes()
RETURNS TRIGGER AS $$
DECLARE
    audit_row audit.events;
BEGIN
    audit_row.actor_id := auth.uid();
    audit_row.operation := TG_OP;
    audit_row.table_name := TG_TABLE_NAME;

    IF (TG_OP = 'INSERT') THEN
        audit_row.new_record := to_jsonb(NEW);
    ELSIF (TG_OP = 'UPDATE') THEN
        audit_row.old_record := to_jsonb(OLD);
        audit_row.new_record := to_jsonb(NEW);
    ELSIF (TG_OP = 'DELETE') THEN
        audit_row.old_record := to_jsonb(OLD);
    END IF;

    INSERT INTO audit.events (actor_id, operation, table_name, old_record, new_record) 
    VALUES (audit_row.actor_id, audit_row.operation, audit_row.table_name, audit_row.old_record, audit_row.new_record);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
