import { CreditCard, HelpCircle, Phone, Settings, Shield, User, Wallet } from 'lucide-react';

import { HatidIconTile, HatidTrustPill, HatidWordmark } from '../../components/hatid-brand';

function SectionCard({ title, detail, children }: { title: string; detail: string; children: React.ReactNode }) {
  return (
    <section className="rounded-[1.75rem] border border-slate-200 bg-white p-4 shadow-sm">
      <div className="mb-4 flex items-start justify-between gap-3">
        <div>
          <p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Preview module</p>
          <h2 className="mt-1 text-lg font-black tracking-tight text-slate-900">{title}</h2>
          <p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p>
        </div>
        <HatidTrustPill tone="slate">Prototype-safe</HatidTrustPill>
      </div>
      {children}
    </section>
  );
}

function Row({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) {
  return (
    <div className="flex items-start gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-3">
      <HatidIconTile>{icon}</HatidIconTile>
      <div>
        <h3 className="text-sm font-black text-slate-900">{title}</h3>
        <p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p>
      </div>
    </div>
  );
}

export default function WalletSafetyPreviewPage() {
  return (
    <main className="min-h-screen bg-slate-950 px-4 py-6 text-slate-900">
      <div className="mx-auto min-h-[820px] w-full max-w-[390px] overflow-hidden rounded-[2.5rem] border-[8px] border-slate-900 bg-slate-50 shadow-2xl">
        <header className="bg-[#0033CC] px-6 pb-8 pt-14 text-white">
          <HatidWordmark light large tagline="Trust, safety, and account clarity." />
          <h1 className="mt-8 text-3xl font-black tracking-[-0.04em]">Ops-safe passenger modules.</h1>
          <p className="mt-3 text-sm leading-6 text-blue-50">A polished direction for wallet, safety, support, and account screens before backend authority is wired.</p>
        </header>

        <div className="space-y-4 px-5 py-5">
          <SectionCard title="Wallet" detail="Balances and payments must stay server-owned.">
            <div className="rounded-2xl bg-[#0033CC] p-4 text-white">
              <p className="text-[10px] font-black uppercase tracking-[0.18em] text-blue-100">Hatid Wallet</p>
              <h3 className="mt-1 text-2xl font-black">Ledger-safe preview</h3>
              <p className="mt-2 text-xs leading-5 text-blue-50">No client-side balance editing, fake charges, or implied production payment authority.</p>
            </div>
            <div className="mt-3 space-y-3">
              <Row icon={<CreditCard size={19} />} title="Payment methods" detail="GCash, Maya, card, and cash labels stay display-only until real PSP rules exist." />
              <Row icon={<Wallet size={19} />} title="Ledger wording" detail="Receipt, fare, refunds, and balances should be generated by audited backend flows." />
            </div>
          </SectionCard>

          <SectionCard title="Safety" detail="Safety actions need operations workflow before launch.">
            <div className="space-y-3">
              <Row icon={<Shield size={19} />} title="Share trip" detail="Family sharing can be designed now, but live delivery needs backend status and permissions." />
              <Row icon={<Phone size={19} />} title="Safety help" detail="No emergency-response promise until escalation, audit logs, and support staffing exist." />
              <Row icon={<HelpCircle size={19} />} title="Report issue" detail="Incident reporting should capture evidence, timestamps, and operator resolution states." />
            </div>
          </SectionCard>

          <SectionCard title="Account" detail="Light, trustworthy, and Filipino-first profile shell.">
            <div className="space-y-3">
              <Row icon={<User size={19} />} title="Maria Santos" detail="Profile display should later read from Supabase profile records." />
              <Row icon={<Settings size={19} />} title="Preferences" detail="Language, notifications, privacy, and accessibility settings." />
            </div>
          </SectionCard>
        </div>
      </div>
    </main>
  );
}
